# Generated by Django 5.1.3 on 2025-01-26 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('transcription', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('corrected_text', models.TextField()),
                ('errors', models.JSONField()),
                ('generated_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eng.generatedword')),
            ],
        ),
    ]
